app:
  port: 8081
  datasource:
    driver: postgres
    host: localhost
    port: 5432
    database: auto_ci_service_db
    username: user_auto_ci_db
    password: secret
  redis:
    host: localhost
    port: 6379
  logging:
    development: true

  kafka:
    bootstrapServers: localhost:9092
    clientId: auto-ci-service-public
    admin:
      topics:
        - name: auto-ci-service-logs-topic
          partitions: 1
          replicationFactor: 1
          retention: 72h
        - name: auto-ci-http-request-topic
          partitions: 1
          replicationFactor: 1
          retention: 72h
    consumer:
      clientId: auto-ci-service-consumer
      handlerMappings:
        UploadFileLogsHandler:
          topic: auto-ci-service-logs-topic
          groupId: auto-ci-service-logs-topic.UploadFileLogsHandler.local
          enable: true
  services:
    buddy:
      BaseUrl: https://api.buddy.works
      AccessToken: ${BUDDY_ACCESS_TOKEN}
    gcs:
      ProjectID: "cross-platform-service"
      Bucket: "auto_ci_service"
      CredentialJSON: ${GCS_CREDENTIALS_JSON}