app:
  path: /auto-ci-service
  name: AutoCI Public Service
  security:
    http:
      publicUrls:
        - /actuator/health
        - /actuator/info
        - /v1/integrations
        - /v1/repositories/*
        - /v1/projects