app:
  path: /auto-ci-service
  name: AutoCI Public Service
  security:
    http:
      publicUrls:
        - /actuator/health
        - /actuator/info
        - /v1/repositories/*
        - /v1/projects
        - /v1/projects/*
        - /v1/pipelines
        - /v1/webhooks/*
        - /v1/auth/*
        - /v1/services/*
        - /v1/services
      protectedUrls:
        - { urlPattern: "/v1/integrations", method: POST,roles: [ "MOBILE_APP" ], unauthorizedWwwAuthenticateHeaders: [ "Bearer" ] }
        - { urlPattern: "/v1/integrations", method: GET,roles: [ "MOBILE_APP" ], unauthorizedWwwAuthenticateHeaders: [ "Bearer" ] }
