app:
  datasource:
    driver: postgres
    host: localhost
    port: 5432
    database: auto_ci_service_db
    username: user_auto_ci_db
    password: secret
  redis:
    host: localhost
    port: 6379
  logging:
    development: true
  security:
    http:
      jwt.publicKey: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAibfYgV1ACadMfuvl5VsR
        V0H/llbi+zB0f6kTSQ0VwzNR9eYbn8vFUaf3RXA8rxdICtKq8dB23F+2+GICIkjt
        cHwC1DtcvfxbpOPLYCrZKLntlzRR2UJOzKTq0JP+ea/zydEYIHR9uVIZarw1vz9R
        LqtiIvZZFUQtDmnc9f7R9kp6XmZgoqg8/hMZ7SF9GvDmdDZSjLCoKrKXHO3a2djn
        L7FwbiOr8Qx2Zlbm+rzZ3ovIXvskIJqg/S7PFg55Xt8oxL4NxaqzxiEVnZMqEGba
        pLzetqErEg73L93r7DdnSc4O55qTrRxXMWE+pRx1jWAFdcQL0kZ1TJf/OnNXKKHw
        aQIDAQAB
        -----END PUBLIC KEY-----
  pubsub:
    Stub: true
  kafka:
    bootstrapServers: localhost:9092
    clientId: auto-ci-service-public
    admin:
      topics:
        - name: auto-ci-service-logs-topic
          partitions: 1
          replicationFactor: 1
          retention: 72h
        - name: auto-ci-http-request-topic
          partitions: 1
          replicationFactor: 1
          retention: 72h
    producer:
      flushMessages: 1
      flushFrequency: 1s
      eventMappings:
        UploadFileLogsEvent:
            topicName: auto-ci-service-logs-topic
            transactional: false
        RequestCompletedEvent:
          topicName: auto-ci-http-request-topic
          transactional: false

  services:
    github:
      BaseURL: https://api.github.com
    encrypt:
        key: "1234567890123456"
    buddy:
      BaseUrl: https://api.buddy.works
      AccessToken: ${BUDDY_ACCESS_TOKEN}

